[package]
name = "xrpl_binary_codec"
version = "0.2.0"
edition = "2021"

[dependencies]
serde = { version = "1", features = ["derive"]}
serde_json = "1"
hex = "0.4"
bs58 = "0.4"
sha2 = "0.9"
libsecp256k1 = "0.5"
xrpl_types = { path = "../xrpl_types", version = "0.2" }