[package]
name = "xrpl_cli"
description = "A CLI for the XRP Ledger"
version = "0.4.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/gmosx/xrpl_sdk_rust/tree/main/xrpl_sdk_jsonrpc"
keywords = ["xrpl", "ledger", "cli"]
authors = ["George Moschovitis <gmosx@reizu.org>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = { version = "3.1", features = ["derive"] }
xrpl_sdk_jsonrpc = { path = "../xrpl_sdk_jsonrpc", version = "0.8" }
tokio = { version = "1", features = ["full"] }
serde = { version = "1", features = ["derive"]}
serde_json = "1"
tracing = "0.1"
tracing-subscriber = "0.2"

[[bin]]
name = "xrpl"
path = "src/main.rs"