[package]
name = "xrpl_cli"
description = "A CLI for the XRP Ledger"
version = "0.1.0"
license = "MIT OR Apache-2.0"
repository = "https://github.com/gmosx/xrpl_sdk_rust/tree/main/xrpl_sdk_jsonrpc"
keywords = ["xrpl", "ledger", "cli"]
authors = ["George Moschovitis <gmosx@reizu.org>"]
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
clap = "3.1"